linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - structcheck
    - interfacer
    - golint
    - scopelint
    - ifshort
    - deadcode
    - exhaustivestruct
    - nosnakecase
    - varcheck
    # not used
    - tagalign
    - depguard
    - exhaustruct
    - wrapcheck
    - godox
    - goerr113
    - wsl

issues:
  max-same-issues: 0
  exclude-rules:
    - path: '(.+)_test\.go'
      linters: [nlreturn, funlen, containedctx]
    - path: '(.+)_test\.go'
      text: "variable name 'tt' is too short for the scope of its usage"
linters-settings:
  nlreturn:
    block-size: 2
  gci:
    sections:
      - standard
      - default
      - prefix(runout)
  gofumpt:
    module-path: runout
  ireturn:
    allow:
      - error
      - stdlib
      - github.com/jackc/pgx/v5.Tx
