version: '3'

dotenv:
  - .env

tasks:
  run:
    cmds:
      - go run main.go

  devdb.up:
    cmds:
      - docker-compose up
  devdb.down:
    cmds:
      - docker-compose down

  migration.create:
    cmds:
      - migrate create -seq -ext sql -dir ./internal/db/migrations/ {{.CLI_ARGS}}

  migration:
    cmds:
      - migrate -database postgres://app:app@localhost:5432/app?sslmode=disable -path ./internal/db/migrations/ {{.CLI_ARGS}}

  gen.sqlc:
    cmds:
      - sqlc generate

  ngrok.start:
    cmds:
      - ngrok start runout

  dbtunnel:
    cmds:
      - ssh -L 5432:localhost:5432 -N app@$PROD_SERVER_HOST
