version: '3'

dotenv:
  - .env

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  test:
    cmds:
      - go test ./...

  gen:
    cmds:
      - go generate ./...

  run:
    cmds:
      - go run main.go

  db.up:
    cmds:
      - docker-compose up
  db.down:
    cmds:
      - docker-compose down

  ngrok.start:
    cmds:
      - ngrok start runout

  dbtunnel:
    cmds:
      - ssh -L 5432:localhost:5432 -N app@$PROD_SERVER_HOST
