version: '3'

tasks:
  run:
    cmds:
      - go run main.go

  devdb.up:
    cmds:
      - docker-compose up
  devdb.down:
    cmds:
      - docker-compose down

  migration.create:
    cmds:
      - migrate create -seq -ext sql -dir ./internal/db/migrations/ {{.CLI_ARGS}}

  # TODO: remove pg creds hardcode
  migration:
    cmds:
      - migrate -database postgres://postgres:postgres@localhost:5432/mydatabase?sslmode=disable -path ./internal/db/migrations/ {{.CLI_ARGS}}
