name: "runOut CI"
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: run tests
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
      - name: build
        run: |
          GOOS=linux GOARCH=amd64 go build -o runout-linux-amd64
          GOOS=darwin GOARCH=arm64 go build -o runout-darwin-arm64
      - name: create-archive
        run: tar -czf migrations.tar.gz -C ./migrations .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            runout-linux-amd64
            runout-darwin-arm64
            migrations.tar.gz
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /app
            # останавливаем сервис
            sudo systemctl stop runout.service && echo "service stopped"
            # Обновляем приложение
            rm -rf runout && echo "old runout removed"
            curl -L -o runout https://github.com/Hrom-in-space/runOut/releases/download/${{ github.ref_name }}/runout-linux-amd64 && echo "new runout downloaded"
            chmod +x runout && echo "runout is executable"
            # Накатываем миграции
            rm -rf migrations && echo "old migrations removed"
            mkdir -p migrations && echo "new migrations dir created"
            curl -L -o migrations.tar.gz https://github.com/Hrom-in-space/runOut/releases/download/${{ github.ref_name }}/migrations.tar.gz && echo "new migrations downloaded"
            tar -xzvf migrations.tar.gz -C migrations && echo "migrations extracted"
            rm -rf migrations.tar.gz && echo "migrations archive removed"
            migrate -database postgres://app:app@localhost:5432/app?sslmode=disable -path ./migrations/ up && echo "migrations applied"
            # Запускаем сервис
            sudo systemctl start runout.service && echo "service started"
