name: "runOut CI"
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: run tests
        run: go test ./...
      - name: build
        run: |
          GOOS=linux GOARCH=amd64 go build -o runout-linux-amd64
          GOOS=darwin GOARCH=arm64 go build -o runout-darwin-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            runout-linux-amd64
            runout-darwin-arm64
